### ISSUE TITLE
Save sunburst plots as png / jpeg

### ISSUE THREAD

**Issue by AniekMarkus** [darwin-eu/TreatmentPatterns#1]
**Is your feature request related to a problem? Please describe.**
Sunburst plots are currently in html format only, this is difficult to use in reports/ publications etc.

**Describe the solution you'd like**
Save sunburst plot in (a more) easily usable format, e.g. png / jpeg. 

**Describe alternatives you've considered**
Standard snapshot tools in R don't work. 

**Additional context**
Sunburst plots are custom created with html/ javascript, standard sunburst plots do not allow visualising combinations.

**Comment by mvankessel-EMC** [comment]
ee4a68f2ca4054679fdf092b2b26a45cc50348fa: Functionality added using webshot2, which can take PNG screenshots of an HTML file. It shadows the webshot2::webshot function, but with some default values that seem to work well.

**Comment by AniekMarkus** [comment]
On my laptop (Mac) this function gives an empty (white/blank) png file when trying to screenshot a sunburst plot. This might have to do with local file restrictions.

**Comment by mvankessel-EMC** [comment]
> On my laptop (Mac) this function gives an empty (white/blank) png file when trying to screenshot a sunburst plot. This might have to do with local file restrictions.

Could you send me the HTML file you're using. The function is specifically looking at HTML tags to reference the right object to screenshot. I would like to rule that out first.

**Comment by AniekMarkus** [comment]
I tried using the example in the vignette (for non-OMOP databases), then used the new function on the resulting "IPCI_default_all_sunburstplot.html" file.

I have the same issue using the webshot function on its own (and it is the problem I kept running into earlier when I wanted to add this functionality to the package...).

**Comment by AniekMarkus** [comment]
Updating the package to the newest version (0.1.0) has fixed the issue.

**Comment by mvankessel-EMC** [comment]
> Updating the package to the newest version (0.1.0) has fixed the issue.

Version >= 0.1.0 of webshot2 is now required (71f48668c548d8a4e87e66604e0cb04e709d7cbd).
