### ISSUE TITLE
Not installable with remotes

### ISSUE THREAD

**Issue by mvankessel-EMC** [darwin-eu/TreatmentPatterns#3]
The TreatmentPatterns package is not installable using:
```
remotes::install_github("darwin-eu/TreatmentPatterns")
```

Which gives the following error

```
Installing package into ‘../Documents/.switchr/TestEnv’
(as ‘lib’ is unspecified)
ERROR: dependencies 'FeatureExtraction', 'OhdsiSharing' are not available for package 'TreatmentPatterns'
* removing '../Documents/.switchr/TestEnv/TreatmentPatterns'
```

The following dependencies are not available:
1. FeatureExtraction
2. OhdsiSharing

When investigating the dependencies using the pak package

```
pak::pkg_deps("darwin-eu/TreatmentPatterns")
```

gives

```
Error:                                                                      
! error in pak subprocess
Caused by error: 
! Cannot install packages:
* darwin-eu/TreatmentPatterns:
  * Can't install dependency FeatureExtraction
  * Can't install dependency OhdsiSharing
* FeatureExtraction: Can't find package called FeatureExtraction, OhdsiSharing.
* OhdsiSharing: Can't find package called FeatureExtraction, OhdsiSharing.
```

The _DESCRIPTION_ file has the following imports

```
Imports: 
    Andromeda,
    DatabaseConnector,
    data.table,
    dplyr,
    SqlRender,
    stringr,
    stringi,
    readr,
    rjson,
    reshape2,
    googleVis,
    RJSONIO,
    FeatureExtraction,
    OhdsiSharing,
    R.utils
```

However [_FeatureExtraction_](https://github.com/OHDSI/FeatureExtraction) and [_OhdsiSharing_](https://github.com/OHDSI/OhdsiSharing) are OHDSI packages from GitHub and are not found (I'm guessing it looks for them on CRAN).

I'd suggest the following for the _DESCRIPTION_ file; which can automatically be done using **roxygen2**.

```
Imports: 
    Andromeda,
    DatabaseConnector,
    data.table,
    dplyr,
    SqlRender,
    stringr,
    stringi,
    readr,
    rjson,
    reshape2,
    googleVis,
    RJSONIO,
    R.utils
Remotes:
    OHDSI/FeatureExtraction,
    OHDSI/OhdsiSharing
```

**Comment by mvankessel-EMC** [comment]
DESCRIPTION file has been updated and TreatmentPatterns is now installable using:

`remotes::install_github("darwin-eu/TreatmentPatterns")`

**Comment by AniekMarkus** [comment]
For me the package is no longer installable using "clean and rebuild" locally:

ERROR: installing package DESCRIPTION failed for package ‘TreatmentPatterns’

**Comment by mvankessel-EMC** [comment]
> For me the package is no longer installable using "clean and rebuild" locally:
> 
> ERROR: installing package DESCRIPTION failed for package ‘TreatmentPatterns’

There was an issue in the DESCRIPTION file under suggested packages. This is now fixed, the package is buildable and installable again.
